### ISSUE TITLE
Update `bpf_override_return` description

### ISSUE THREAD

**Issue by dylandreimerink** [isovalent/ebpf-docs#26]
The description we get from libbpf says

> Also, the helper is only available for the architectures having the CONFIG_FUNCTION_ERROR_INJECTION option. As of this writing, x86 architecture is the only one to support this feature.

Since then, more architectures got support, would be nice to give the description an update in the docs.

**Comment by ShawnZhong** [comment]
It is already fixed in upstream: https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=c6ca31981b545ad3081007b6aa88b6aab1b0cece, sitting in the `bpf-next` repo.

**Comment by ShawnZhong** [comment]
Seems that it's already removed in this repo as well: https://github.com/isovalent/ebpf-docs/commit/bc0bc07d4a4d089978467130f36287e659e8b6cd
